# Generated by Django 5.2.7 on 2025-10-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician'), ('representative', 'Representative')], default='customer', max_length=20),
        ),
    ]
