# Generated by Django 5.2.7 on 2025-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_profile_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
