# Generated by Django 5.2.7 on 2026-04-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_servicerequest_attachment_servicerequest_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician'), ('agent', 'Agent')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_links', to='service.profile')),
                ('technician', models.ForeignKey(limit_choices_to={'user_type': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='service.profile')),
            ],
            options={
                'unique_together': {('agent', 'technician')},
            },
        ),
        migrations.DeleteModel(
            name='agentTechnician',
        ),
    ]
