# Generated by Django 5.2.7 on 2026-04-25 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_servicerequestpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests_agent', to='service.profile'),
        ),
    ]
